### Particle Image Function
### Version: 1.0.4
### Width: 30
### Height: 30
### ParticleType: dripping_obsidian_tear

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dripping_obsidian_tear ^2.4 ^1 ^1.6 0.01 0.01 0.01 0 1 force @a
particle minecraft:dripping_obsidian_tear ^2.4 ^1 ^-1.6 0.01 0.01 0.01 0 1 force @a
particle minecraft:dripping_obsidian_tear ^-2.4 ^1 ^1.6 0.01 0.01 0.01 0 1 force @a
particle minecraft:dripping_obsidian_tear ^-2.4 ^1 ^-1.6 0.01 0.01 0.01 0 1 force @a
particle minecraft:dripping_obsidian_tear ^0 ^1 ^2.4 0.01 0.01 0.01 0 1 force @a
particle minecraft:dripping_obsidian_tear ^0 ^1 ^-2.4 0.01 0.01 0.01 0 1 force @a